### ISSUE TITLE
Allow Laravel 5.3

### ISSUE THREAD

**Issue by alexbowers** [core-system/bootstrap-form#1]

**Comment by molbi** [comment]
Hi, thank you for an issue. 

The version for L5.3 is now in dev-laravel-5.3 branch. If you will need it immediately, you should ad d to your composer.json this

`"repositories": [ {"type": "git", "url": "https://github.com/core-system/bootstrap-form" } ],`

and require

`"core-system/bootstrap-form": "dev-laravel-5.3"`

or you should wait for release, which will be later this day.

**Comment by alexbowers** [comment]
Since there are no actual changes to the code, would it not make sense to require `^5.2` so that it allows 5.2.* and 5.3.*?

**Comment by molbi** [comment]
Hi, you are right. But I had an issue with L5.2 and new laravelcollective on other my project, but i didnt have time to test it properly :( this is was just quicker solution for using this package on L5.3, this is reason, why i wrote you this possibility to use this.

**Comment by alexbowers** [comment]
Its okay, it isnt urgent for me. I was looking at different bootstrap helpers a few days ago. I dont actually use it currently, and can hold off on it, for a proper solution to be done, that isn't rushed. Im in no hurry for it :)
