### ISSUE TITLE
Unbound version constraints (>=1.0.2) should be avoided

### ISSUE THREAD

**Issue by MadaSociety** [core-system/bootstrap-form#2]
Hello,
After run "composer diagnose", I have warning.

`Checking composer.json: WARNING
require.core-system/bootstrap-form : unbound version constraints (>=1.0.2) should be avoided`

How can fix it ?

Thank you.

**Comment by marley-ma** [comment]
Hello,
it's documentation mistake. You can fix it by changing line in `composer.json` file from:

```json
  "core-system/bootstrap-form": ">=1.0.0"
```
to
```json
  "core-system/bootstrap-form": "^1.0.0"
```

[Reason why warning was fired](https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md)
