### ISSUE TITLE
Laravel 5.4 / Collective/Html 5.4 compatibility plan ?

### ISSUE THREAD

**Issue by Cyrille37** [core-system/bootstrap-form#7]
Hi,
It seems to not be compatible with Laravel 5.4 and Collective/Html 5.3 : 

`ErrorException: Declaration of Core\BootstrapForm\BootstrapFormBuilder::select($name, $list = Array, $selected = NULL, $options = Array) should be compatible with Collective\Html\FormBuilder::select($name, $list = Array, $selected = NULL, array $selectAttributes = Array, array $optionsAttributes = Array) in /.../vendor/core-system/bootstrap-form/src/BootstrapFormBuilder.php:0
`

Thanks a lot for your work.
Cheers

**Comment by marley-ma** [comment]
Hi  @Cyrille37 ,
please use "dev-master" version instead of v1.0.3 release. Mentioned changes will be released as part of v1.0.4 release.

Cheers

**Comment by kojilab** [comment]
Still getting this issue after updating to 1.1.1
