### ISSUE TITLE
v1.0.4 not compatible with laravelcollective/html v5.2.6

### ISSUE THREAD

**Issue by jonathanabrahams** [core-system/bootstrap-form#8]
composer update from 1.0.3 to 1.0.4 breaks

Declaration of Core\BootstrapForm\BootstrapFormBuilder::select() should be compatible with Collective\Html\FormBuilder::select($name, $list = Array, $selected = NULL, $options = Array)

to fix this issue i forced my composer.json to 1.0.3

**Comment by marley-ma** [comment]
Hi @jonathanabrahams,
first i want to thank you for your pull request. I changed release from v1.0.4 for v1.1.0 and documentation for more transparency of version conventions. 

So, now will be all `v1.0.*` releases compatible with `laravelcollective/html`:`5.3.*` and bellow versons. And all `v1.1.*` with `laravelcollective/html`:`5.4.*`

Cheers MarleyMA
